name: build

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      issues: write
      pull-requests: write
    env:
      GITHUB_EVENT_NAME: ${{ github.event_name }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/checkout@v4
        with:
          repository: laminlabs/lndocs
          ssh-key: ${{ secrets.READ_LNDOCS }}
          path: lndocs
          ref: main
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - run: pip install "laminci@git+https://x-access-token:${{ secrets.LAMIN_BUILD_DOCS }}@github.com/laminlabs/laminci"
      - run: nox -s lint
      - run: nox -s install
      - run: nox -s test
      - run: nox -s docs
      - run: rm -r ./_build/html/.doctrees # do not want to deploy with cloudflare
        if: matrix.python-version == '3.12'
      - uses: cloudflare/wrangler-action@v3
        id: cloudflare
        if: matrix.python-version == '3.12'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 472bdad691b4483dea759eadb37110bd
          command: pages deploy "_build/html" --project-name=pertdb
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: edumserrano/find-create-or-update-comment@v2
        if: ${{ matrix.python-version == '3.12' && github.event_name == 'pull_request' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "Deployment URL"
          comment-author: "github-actions[bot]"
          body: |
            Deployment URL: ${{ steps.cloudflare.outputs.deployment-url }}
          edit-mode: replace
